### ISSUE TITLE
Multiple domains - multiple base_dn entries 

### ISSUE THREAD

**Issue by nilldot** [DeepWoods/gsuiteRadius#1]
Hi,
Not sure how you guys handled multi-domain environment in regards to base_dn search filter in config file for the same google ldap server?

As an example, we have users in domainA.com and domainb.com, base_dn will be different for each domain for both users and groups in Google realms. We have 10+ Domains to deal with. Any advise for wilcard/variable based base_dn search would be much appreciated.

Thank you

**Comment by DeepWoods** [comment]
We don't have multiple domains in GSuite so I haven't dealt with this issue.  The first thing that comes to mind though is configuring multiple realms in proxy.conf for FreeRADIUS.

**Comment by nilldot** [comment]
Thanks
