### ISSUE TITLE
What is the use of the /radius/id_rsa.txt

### ISSUE THREAD

**Issue by jfboulard** [DeepWoods/gsuiteRadius#12]
Hi!
I am in the process of deploying your solution, and I am wondering what is the use of the /radius/id_rsa.txt file?

I have search for an answer, but fail at the moment.

Thank you for your good work!

**Comment by DeepWoods** [comment]
It's a ssh key and leftover from my own setup and not used unless you wanted to add Let's Encrypt certificates.  That's something optional that I was using and left it in the configs commented out in case someone else wanted to use it on their own.  You can follow how it's used in [radius/init.sh](https://github.com/DeepWoods/gsuiteRadius/blob/master/radius/init.sh) but it's not necessary and would be something specific for your own setup.
