### ISSUE TITLE
Error :  norsp ** Access-Request

### ISSUE THREAD

**Issue by feller23** [DeepWoods/gsuiteRadius#4]
I configured the container to connect with my google ldap credentials  but everytime i initiate a connection , its shown that the connection has been received but it still gives  "norsp ** Access-Request" in debugged output. Below is a snapshot of the debugged output

User-Name = "studenttest@utg.edu.gm"
	NAS-IP-Address = 172.16.0.34
	Service-Type = Framed-User
	Framed-MTU = 1400
	Called-Station-Id = "96-AC-B9-B4-A2-4C:Radius"
	Calling-Station-Id = "5A-9D-C0-DC-C0-61"
	NAS-Identifier = "96acb9b4a24c"
	NAS-Port-Type = Wireless-802.11
	Acct-Session-Id = "E0E24FC5F48AB748"
	Connect-Info = "CONNECT 0Mbps 802.11b"
	EAP-Message = 0x02bc001b0173747564656e7474657374407574672e6564752e676d
	Message-Authenticator = 0x7eb8361d660d162487e1fe749a618157
	WLAN-Pairwise-Cipher = 1027076
	WLAN-Group-Cipher = 1027076
	WLAN-AKM-Suite = 1027073
	Authenticator-Field = 0x8e994796bbb8529c81bf1d5c7ca9c199
2021-08-02 08:37:45.752986 (3) ** norsp ** Access-Request Id 4 eth0:212.60.92.82:38110 -> 192.168.5.5:1812
2021-08-02 08:37:45.752986 (3) Cleaning up request packet ID 4
2021-08-02 08:37:46.562574 (8) Access-Request Id 4 eth0:212.60.92.82:38110 -> 192.168.5.5:1812 +14.022

**Comment by DeepWoods** [comment]
Hard to tell with just a snippet of the debug output.  Did you add your NAS client(s) in clients.conf or through Daloradius in SQL?  Also, make sure your NAS secret matches.  There's not a firewall that could be blocking ports?  Just a few thoughts.

**Comment by feller23** [comment]
Am using the UNIFI controller with multiple access points so should i add the controller IP or rhe access points IP

**Comment by DeepWoods** [comment]
The access point IPs, not the controller IP.  If all the AP's are in the same subnet range, it's easier to add it in clients.conf.   Something like 
`client unifi-ap-network {
	ipaddr = 10.1.2.0
	netmask = 24
	secret = SuP3rSecR7t
	shortname = unifi-ap-network
	nas_type = "other"
}`
It's easier and probably more secure to add them one by one via Daloradius though if they're not all in their own subnet.
